In [2]:
import pandas as pd

In [3]:
result = pd.read_csv('top100_recommendations.csv')

In [4]:
result.head(100)

,User ID,Top 100 Items,Top 100 Scores
0,0,[59074 66281 65735 57553 67810 58098 64530 743...,[0.06557453 0.04773502 0.04167578 0.03908418 0...
1,1,[70738 60091 73222 70243 69269 70074 58575 597...,[0.10013087 0.08872008 0.0538477 0.04962774 0...
2,2,[70903 67934 58005 34598 58098 73496 57413 611...,[0.10340261 0.07147983 0.03447064 0.02902913 0...
3,3,[59577 68298 76421 74112 66281 74709 70738 596...,[0.07419483 0.07285628 0.06337299 0.0511923 0...
4,4,[59689 67980 67978 76421 65367 69269 75047 590...,[0.11222869 0.06815927 0.06753546 0.05091639 0...
...,...,...,...
95,95,[78051 78156 77596 61116 61379 61283 59897 646...,[0.12863272 0.11435682 0.09496205 0.06905223 0...
96,96,[61645 62075 63649 62771 63826 67519 29168 729...,[0.06420247 0.06174402 0.04579696 0.0441625 0...
97,97,[70243 66281 68298 60917 61645 70015 69515 641...,[0.20925106 0.06134517 0.04259695 0.03445125 0...
98,98,[24786 21963 35179 53649 15688 55897 41978 176...,[0.08768126 0.07623345 0.04643966 0.02909459 0...
99,99,[69269 68298 70243 59002 61645 69416 70738 671...,[0.11992909 0.09524076 0.04109844 0.03710768 0...

In [5]:
len(result)

630272